// ACTIONS
export const  FETCH_RAMPS_STARTED = 'FETCH_RAMPS_STARTED';
export const FETCH_RAMPS_SUCCEEDED = 'FETCH_RAMPS_SUCCEEDED';
export const FETCH_RAMPS_FAILED = 'FETCH_RAMPS_FAILED';

export const FETCH_TOTAL_RAMPS_PER_CONSTRUCTION_MATERIAL_STARTED = 'FETCH_TOTAL_RAMPS_PER_CONSTRUCTION_MATERIAL_STARTED';
export const FETCH_TOTAL_RAMPS_PER_CONSTRUCTION_MATERIAL_SUCCEEDED = 'FETCH_TOTAL_RAMPS_PER_CONSTRUCTION_MATERIAL_SUCCEEDED';
export const FETCH_TOTAL_RAMPS_PER_CONSTRUCTION_MATERIAL_FAILED = 'FETCH_TOTAL_RAMPS_PER_CONSTRUCTION_MATERIAL_FAILED';

export const FETCH_TOTAL_RAMPS_PER_SIZE_STARTED = 'FETCH_TOTAL_RAMPS_PER_SIZE_STARTED';
export const FETCH_TOTAL_RAMPS_PER_SIZE_SUCCEEDED = 'FETCH_TOTAL_RAMPS_PER_SIZE_SUCCEEDED';
export const FETCH_TOTAL_RAMPS_PER_SIZE_FAILED = 'FETCH_TOTAL_RAMPS_PER_SIZE_FAILED';

export const CHOOSE_FOR_DETAIL = 'CHOOSE_FOR_DETAIL';
export const CLEAR_DETAIL = 'CLEAR_DETAIL';
export const IDLE_MAP = 'IDLE_MAP';